export interface ICurrency {
    timestamp: number
    base: string
    success: boolean
    date: string
    rates: {
        ANG: number
        SVC: number
        CAD: number
        XCD: number
        MVR: number
        HRK: number
        AUD: number
        MWK: number
        XAG: number
        MAD: number
        PHP: number
        NAD: number
        GNF: number
        KES: number
        MZN: number
        BTN: number
        MGA: number
        AZN: number
        XAU: number
        RON: number
        CHF: number
        EGP: number
        BSD: number
        TWD: number
        GGP: number
        LVL: number
        MMK: number
        WST: number
        ILS: number
        BHD: number
        GBP: number
        TZS: number
        SDG: number
        LAK: number
        DJF: number
        BYN: number
        MRO: number
        RWF: number
        PEN: number
        EUR: number
        ZMK: number
        RSD: number
        INR: number
        MUR: number
        BWP: number
        GEL: number
        KMF: number
        UZS: number
        RUB: number
        CUC: number
        BGN: number
        JOD: number
        NGN: number
        BDT: number
        PKR: number
        BRL: number
        KZT: number
        CVE: number
        HNL: number
        NZD: number
        ERN: number
        NPR: number
        ZMW: number
        FKP: number
        DZD: number
        JMD: number
        CRC: number
        GMD: number
        PLN: number
        AMD: number
        BMD: number
        BZD: number
        BBD: number
        SBD: number
        IDR: number
        ALL: number
        IQD: number
        BIF: number
        HKD: number
        GIP: number
        BAM: number
        LKR: number
        QAR: number
        SAR: number
        TOP: number
        SEK: number
        ZAR: number
        ARS: number
        MYR: number
        BYR: number
        KPW: number
        CZK: number
        STD: number
        BTC: number
        ZWL: number
        LSL: number
        COP: number
        PAB: number
        IRR: number
        LTL: number
        XPF: number
        XOF: number
        XDR: number
        OMR: number
        CNY: number
        NIO: number
        AOA: number
        SCR: number
        MOP: number
        ISK: number
        VND: number
        VES: number
        USD: number
        UYU: number
        VEF: number
        UGX: number
        UAH: number
        DOP: number
        TTD: number
        BOB: number
        NOK: number
        TND: number
        TMT: number
        SGD: number
        TJS: number
        GHS: number
        THB: number
        KHR: number
        ETB: number
        PGK: number
        CLP: number
        AED: number
        SYP: number
        LRD: number
        SRD: number
        KYD: number
        CUP: number
        SLL: number
        LYD: number
        SLE: number
        SHP: number
        FJD: number
        IMP: number
        JEP: number
        PYG: number
        KRW: number
        SZL: number
        GYD: number
        MDL: number
        MXN: number
        HTG: number
        JPY: number
        SOS: number
        MNT: number
        AFN: number
        GTQ: number
        CLF: number
        KGS: number
        TRY: number
        YER: number
        HUF: number
        BND: number
        MKD: number
        AWG: number
        CDF: number
        LBP: number
        VUV: number
        XAF: number
        KWD: number
        DKK: number
    }
}